import random
from aima_problem import Problem

class Node:
    """A node in a search tree. Contains a pointer to the parent (the node
    that this is a successor of) and to the actual state for this node."""
    def __init__(self, state, parent=None, action=None, path_cost=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost
        self.depth = 0
        if parent:
            self.depth = parent.depth + 1

    def __repr__(self):
        return f"<Node {self.state}>"

    def expand(self, problem):
        """List the nodes reachable in one step from this node."""
        return [self.child_node(problem, action)
                for action in problem.actions(self.state)]

    def child_node(self, problem, action):
        """Creates the child node generated by applying action to the state."""
        next_state = problem.result(self.state, action)
        next_node = Node(next_state, self, action,
                         self.path_cost + problem.action_cost(self.state, action, next_state))
        return next_node

    def path(self):
        """Return a list of nodes forming the path from the root to this node."""
        node, path_back = self, []
        while node:
            path_back.append(node)
            node = node.parent
        return list(reversed(path_back))

def random_blind_search(problem: Problem, max_depth=1000):
    """
    Simulates a blind random search algorithm. 
    It expands a single random path until it hits the goal or max depth.
    """
    node = Node(problem.initial)
    if problem.is_goal(node.state):
        return node
    
    for _ in range(max_depth):
        actions = problem.actions(node.state)
        if not actions:
            break
            
        action = random.choice(actions)
        node = node.child_node(problem, action)
        
        if problem.is_goal(node.state):
            return node
            
    return node # returns last node if max_depth is reached
